interface ZIF_SIE_FT_1CO_I_ORGM_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 CREATE_ZSIE_FT_1CO_I_ORGM      TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CB3F70',
 DELETE_ZSIE_FT_1CO_I_ORGM      TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CBBF70',
 LOCK_ZSIE_FT_1CO_I_ORGM        TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CA7F70',
 SAVE_ZSIE_FT_1CO_I_ORGM        TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CC3F70',
 UNLOCK_ZSIE_FT_1CO_I_ORGM      TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CABF70',
 UPDATE_ZSIE_FT_1CO_I_ORGM      TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CB7F70',
 VALIDATE_ZSIE_FT_1CO_I_ORGM    TYPE /BOBF/ACT_KEY VALUE '00505680886D1EDAA7FF88A049CBFF70',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZSIE_FT_1CO_I_ORGM,
        BEGIN OF LOCK_ZSIE_FT_1CO_I_ORGM,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZSIE_FT_1CO_I_ORGM,
        BEGIN OF UNLOCK_ZSIE_FT_1CO_I_ORGM,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZSIE_FT_1CO_I_ORGM,
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '00505680886D1EDAA7FF88F4B9719F70',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CA5F70',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CA1F70',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CB1F70',
      END OF ZSIE_FT_1CO_I_ORGM,
      BEGIN OF ZSIE_FT_1CO_I_ORGM_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CC9F70',
      END OF ZSIE_FT_1CO_I_ORGM_LOCK,
      BEGIN OF ZSIE_FT_1CO_I_ORGM_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CC7F70',
      END OF ZSIE_FT_1CO_I_ORGM_MESSAGE,
      BEGIN OF ZSIE_FT_1CO_I_ORGM_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '00505680886D1EDAA7FF88A049CCBF70',
      END OF ZSIE_FT_1CO_I_ORGM_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '00505680886D1EDAA7FF88A049C97F70' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZSIE_FT_1CO_I_ORGM' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '00505680886D1EDAA7FF88F4B971BF70',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZSIE_FT_1CO_I_ORGM             TYPE /BOBF/OBM_GROUP_KEY VALUE '00505680886D1EDAA7FF88F4B976BF70',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZSIE_FT_1CO_I_ORGM             TYPE /BOBF/OBM_NODE_KEY VALUE '00505680886D1EDAA7FF88A049C9BF70',
 ZSIE_FT_1CO_I_ORGM_LOCK        TYPE /BOBF/OBM_NODE_KEY VALUE '00505680886D1EDAA7FF88A049CA3F70',
 ZSIE_FT_1CO_I_ORGM_MESSAGE     TYPE /BOBF/OBM_NODE_KEY VALUE '00505680886D1EDAA7FF88A049C9FF70',
 ZSIE_FT_1CO_I_ORGM_PROPERTY    TYPE /BOBF/OBM_NODE_KEY VALUE '00505680886D1EDAA7FF88A049CAFF70',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  KOKRS                          TYPE STRING VALUE 'KOKRS',
  APPL                           TYPE STRING VALUE 'APPL',
  ORGKEY                         TYPE STRING VALUE 'ORGKEY',
  OBJTYPE                        TYPE STRING VALUE 'OBJTYPE',
  VALTYPE                        TYPE STRING VALUE 'VALTYPE',
  VALUE                          TYPE STRING VALUE 'VALUE',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '00505680886D1EDAA7FF88A049C9DF70',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZSIE_FT_1CO_I_ORGM,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '00505680886D1EDAA7FF88F4B9725F70',
      END OF ZSIE_FT_1CO_I_ORGM,
    END OF SC_VALIDATION .
endinterface.
